# basic options
title: Eva Loaeza
#author: Eva Loaeza  
email: 
description: Economics

github_username:  evaloaeza

header_pages:
- research.md
- teaching.md
 
# Build settings
markdown: kramdown
theme: minima
