# basic options
title: Eva Loaeza
logo: "/images/me.PNG?raw=true" 
#author: Eva Loaeza  
email: 
description: Economics

github_username:

header_pages:
- research.md
- teaching.md
 
# Build settings
markdown: kramdown
theme: minima
