# basic options
title: Eva Loaeza
#author: Eva Loaeza  
email: 
description: Economics

github_username:

header_pages:
- research.md
- teaching.md
 
# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
