# basic options
title: Eva Loaeza
logo: "/images/me.png?raw=true" # your photo (or logo) here
#author: Eva Loaeza  
email: 
description: Economics

github_username:

header_pages:
- research.md
- teaching.md
 
# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
